blueprint:
  name: scenes_initialize2
  description: Fills the scene input_select after home assistant is restarted
  domain: automation
  input:
    scene_parameters:
      name: Scene Parameters
      description: group with all scenes and parameters
      selector:
        entity:
          domain: input_select
variables:
  map: !input scene_map
trigger:
  - platform: homeassistant
    event: start
action:
  - service: automation.turn_off
    entity_id: !input scene_updater

  - service: input_select.set_options
    data_template:
      entity_id: !input scene_selector
      options: |
        {{ (states(map) | from_json).keys() | list }}

# {{ (states(map).keys() }}

  - service: automation.turn_on
    entity_id: !input scene_updater
